- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: sivakumar
  tasks:  
  
  - name: print the variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "cousre is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
  
  - name: print the variables1
    ansible.builtin.debug:
      msg: "cousre is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"