- name: variables from files
  hosts: local
  connection: local
  vars_prompt: 
  - name: COURSE
    prompt: please enter the course
  - name: DURATION
    prompt: please enter the duration
  - name: TRAINER
    prompt: please enter trainer name  
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "cousre is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 
