- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "cousre is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 
