- name: variables
  hosts: local
  connection: local
  vars:
    GREET: "PLAY"
  # vars_files:  
  # - course.yaml 
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:  
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

      #1 command line
      #2 task level
      #3 prompt
      #4 play
      #5 inventory