- name: Devops course information
  hosts: local
  connection: local
  vars:
    course_name: "Devops with AWS"
    duration: 120
    topics:
    - linux
    - shell
    - ansible
    - AWS
    live: true
    tools:
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print course information    
    ansible.builtin.debug:
      msg: "Hello i am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it: {{ live }}, tools covered are: {{ tools }}"