- name: shell Vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr 
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"

          "msg": {
        "changed": true,
        "cmd": "ls -ltr",
        "delta": "0:00:00.006717",
        "end": "2025-01-25 01:50:54.152482",
        "failed": false,
        "msg": "",
        "rc": 0,
        "start": "2025-01-25 01:50:54.145765",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "total 136\n-rw-r--r-- 1 ec2-user ec2-user   112 Jan 19 02:28 02-hello-world.yaml\n-rw-r--r-- 1 ec2-user ec2-user   131 Jan 19 02:28 01-playbook.yaml\n-rw-r--r-- 1 ec2-user ec2-user   305 Jan 22 07:54 04-multi-play.yaml\n-rw-r--r-- 1 ec2-user ec2-user   274 Jan 22 07:54 03-nginx.yaml\n-rw-r--r-- 1 ec2-user ec2-user   294 Jan 22 08:06 05-vars.yaml\n-rw-r--r-- 1 ec2-user ec2-user   478 Jan 22 08:13 06-tasks-vars.yaml\n-rw-r--r-- 1 ec2-user ec2-user   256 Jan 22 08:24 07-vars-files.yaml\ndrwxr-xr-x 4 ec2-user ec2-user  4096 Jan 24 01:53 ansiblee\n-rw-r--r-- 1 ec2-user ec2-user    83 Jan 25 01:28 course.yaml\n-rw-r--r-- 1 ec2-user ec2-user   346 Jan 25 01:28 19-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user   216 Jan 25 01:28 18-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user   184 Jan 25 01:28 17-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user   338 Jan 25 01:28 16-conditions.yaml\n-rw-r--r-- 1 ec2-user ec2-user   131 Jan 25 01:28 15-facts.yaml\n-rw-r--r-- 1 ec2-user ec2-user   466 Jan 25 01:28 14-conditions.yaml\n-rw-r--r-- 1 ec2-user ec2-user   510 Jan 25 01:28 13-data-types.yaml\n-rw-r--r-- 1 ec2-user ec2-user   431 Jan 25 01:28 12-vars-preference.yaml\n-rw-r--r-- 1 ec2-user ec2-user   210 Jan 25 01:28 11-vars-args.yaml\n-rw-r--r-- 1 ec2-user ec2-user   204 Jan 25 01:28 10-vars-inventory.yaml\n-rw-r--r-- 1 ec2-user ec2-user   226 Jan 25 01:28 09-vars-inventory.yaml\n-rw-r--r-- 1 ec2-user ec2-user   443 Jan 25 01:28 08-vars-prompt.yaml\n-rw-r--r-- 1 ec2-user ec2-user   588 Jan 25 01:28 inventory.ini\n-rw-r--r-- 1 ec2-user ec2-user 37961 Jan 25 01:28 facts.json\n-rw-r--r-- 1 ec2-user ec2-user  1412 Jan 25 01:34 20-filters.yaml\n-rw-r--r-- 1 ec2-user ec2-user   446 Jan 25 01:50 21-shell-command.yaml",
        "stdout_lines": [
            "total 136",
            "-rw-r--r-- 1 ec2-user ec2-user   112 Jan 19 02:28 02-hello-world.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   131 Jan 19 02:28 01-playbook.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   305 Jan 22 07:54 04-multi-play.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   274 Jan 22 07:54 03-nginx.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   294 Jan 22 08:06 05-vars.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   478 Jan 22 08:13 06-tasks-vars.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   256 Jan 22 08:24 07-vars-files.yaml",
            "drwxr-xr-x 4 ec2-user ec2-user  4096 Jan 24 01:53 ansiblee",
            "-rw-r--r-- 1 ec2-user ec2-user    83 Jan 25 01:28 course.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   346 Jan 25 01:28 19-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   216 Jan 25 01:28 18-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   184 Jan 25 01:28 17-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   338 Jan 25 01:28 16-conditions.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   131 Jan 25 01:28 15-facts.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   466 Jan 25 01:28 14-conditions.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   510 Jan 25 01:28 13-data-types.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   431 Jan 25 01:28 12-vars-preference.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   210 Jan 25 01:28 11-vars-args.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   204 Jan 25 01:28 10-vars-inventory.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   226 Jan 25 01:28 09-vars-inventory.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   443 Jan 25 01:28 08-vars-prompt.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   588 Jan 25 01:28 inventory.ini",
            "-rw-r--r-- 1 ec2-user ec2-user 37961 Jan 25 01:28 facts.json",
            "-rw-r--r-- 1 ec2-user ec2-user  1412 Jan 25 01:34 20-filters.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   446 Jan 25 01:50 21-shell-command.yaml"
        ]
    }

